 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: flask-node-deployment
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: flasknode
   template:
     metadata:
       labels:
         app: flasknode
     spec:
       containers:
       - name: mycluster-free
         image: icr.io/skill/app:latest
         imagePullPolicy: Always
         ports:
         - containerPort: 5000